## spring security 配置
security:
  oauth2:
    client:
      client-id: cloudx
      client-secret: cloudx
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /social/info/*
        - /social/*
        - /log/save
