
server:
  port: 8900

spring:
  application:
    name: @artifactId@
  security:
    user:
      name: cloudx
      password: cloudx


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://cloudx:cloudx@localhost:8900/eureka/
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9